In [1]:
import numpy as np

np.random.seed(42)

In [2]:
A = np.random.randint(1, 11, size=(4, 3))

print("Matrix A:")
print(A)
print("Shape of A:", A.shape)

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape of A: (4, 3)


In [3]:
B = np.random.randint(1, 11, size=(3, 5))

print("Matrix B:")
print(B)
print("Shape of B:", B.shape)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape of B: (3, 5)


In [4]:
assert A.shape[1] == B.shape[0]

print("Matrix dimensions are compatible.")

Matrix dimensions are compatible.


In [5]:
C = np.dot(A, B)

print("Matrix C = A dot B:")
print(C)
print("Shape of C:", C.shape)

Matrix C = A dot B:
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape of C: (4, 5)


In [6]:
print("Total sum of C:", np.sum(C))

Total sum of C: 2188


In [7]:
print("Row-wise sums:", np.sum(C, axis=1))

Row-wise sums: [544 634 514 496]


In [8]:
print("Column-wise sums:", np.sum(C, axis=0))

Column-wise sums: [676 396 470 244 402]
