In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50


In [4]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]


In [7]:
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

Sum: 6
Mean: 2.0
Maximum: 3
Minimum: 1
